services:
  accounts:
    image: "hoangnq011/accounts:latest"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangnq011
  cards:
    image: "hoangnq011/cards:latest"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangnq011
  loans:
    image: "hoangnq011/loans:latest"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangnq011
networks:
  hoangnq011:
    driver: "bridge"