build:
  version: "2.2"

loans:
  message: "Welcome to loans related QA APIs"
  contactDetails:
    name: "Hoang Nguyen - QA Lead"
    email: "hoangnq011@gmail.com"
  onCallSupport:
    - (555) 555-2323
    - (555) 555 3232