spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

loans:
  message: "Welcome to accounts related PROD APIs"
  contactDetails:
    name: "Hoang Nguyen - Product Owner"
    email: "hoangnq011@gmail.com"
  onCallSupport:
    - (555) 555-3333
    - (555) 555 1212